USE QUESTBANK;

CREATE OR REPLACE TABLE TB_CATEGORY(
	CATEGORY_NO		INT			PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_NAME	VARCHAR(20)
)

CREATE OR REPLACE TABLE TB_USER(
	USER_ID		VARCHAR(20)	PRIMARY KEY,
	USER_NICKNAME		VARCHAR(20)	NOT NULL,
	USER_PWD	CHAR(128)	NOT NULL,
	USER_EMAIL VARCHAR(50) NOT NULL,
	USER_ROLE 
	USER_EXP		INT NOT NULL DEFAULT 0,
	REG_TIME	DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	USE_F		CHAR(1)
)

CREATE OR REPLACE TABLE TB_TEST(
	TEST_NO		INT			PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_NO	INT			NOT NULL,
	MANAGER_ID	VARCHAR(20)	NOT NULL,
	TEST_NAME	VARCHAR(20)	NOT NULL,
	TEST_INFO	TEXT			NOT NULL,
	QUEST_CNT	INT			NOT NULL,
	PASS_SOCRE	INT			NOT NULL,
	REG_TIME		DATETIME		NOT NULL,
	USE_F			CHAR(1)
)