USE QUESTBANK;

CREATE OR REPLACE TABLE TB_CATEGORY(
	CATEGORY_NO		INT			PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_NAME		VARCHAR(20)		NOT NULL,
	USE_F			CHAR(1)
)

CREATE OR REPLACE TABLE TB_USER(
	USER_ID			VARCHAR(20),
	USER_NICKNAME	VARCHAR(20),
	USER_PWD			CHAR(128),
	USER_ROLE		VARCHAR(10),
	USER_EXP			INT,
	REG_TIME			DATETIME,
	USE_F				CHAR(1)
)

CREATE OR REPLACE TABLE TB_TEST(
	TEST_NO		INT			PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_NO	INT			NOT NULL,
	MANAGER_ID	VARCHAR(20)	NOT NULL,
	TEST_NAME	VARCHAR(20)	NOT NULL,
	TEST_INFO	TEXT			NOT NULL,
	QUEST_CNT	INT			NOT NULL,
	PASS_SOCRE	INT			NOT NULL,
	REG_TIME		DATETIME		NOT NULL,
	USE_F			CHAR(1)
)